In [1]:
import numpy as np

Во всех задачах необходимо написать код решения внутри функции и проверить его работу, вызвав функцию для данных из условия.

При решении задач запрещается использовать циклы (`for`, `while`) и оператор `if` (даже внутри генераторов).

Везде, где встречаются массивы или матрицы, подразумевается, что это `numpy.array`. 

### 1

Напишите функцию, которая возвращает индексы ненулевых элементов. Например, если на вход поступает массив `array([1, 2, 0, 0, 4, 0])`, то на выходе должен получиться массив `array([0, 1, 4])`.

_Функции, которые могут пригодиться при решении: `.where()`, `.nonzero()`_

In [180]:
def index_nonzero(array):
    ind, *_ = array.nonzero()
    return ind

In [182]:
a = np.array([1, 2, 0, 0, 4, 0])
index_nonzero(a)

array([0, 1, 4])

### 2

Напишите функцию, меняющую все четные значения массива целых чисел на заданное число. Например, если на вход поступает массив `array([3, 5, 1, 0, -3, 22, 213436])` и число `-111`, то на выходе должен получиться массив `array([   3,    5,    1, -111,   -3, -111, -111])`.

In [183]:
def change_array(array, number):
    return np.where((array % 2) == 1, array, number )

In [184]:
#Проверьте корректность работы функции
a = np.array([3, 5, 1, 0, -3, 22, 213436])
change_array(a,-111)


array([   3,    5,    1, -111,   -3, -111, -111])

### 3

Напишите функцию, вычисляющую самое близкое и самое дальнее числа к данному в рассматриваемом массиве чисел. Например, если на вход поступают массив `array([0, 1, 2, 3, 4])` и число 1.33, то ответом будет `(1, 4)`. В случае неоднозначного ответа должно выводиться число с наименьшим индексом.

_Функции, которые могут пригодиться при решении: `.abs()`, `.argmax()`, `.argmin()`_

In [185]:
def closest_value(array, value):
    dist = np.abs(array - value)
    mn = array[np.argmin(dist)]
    mx = array[np.argmax(dist)]
    return (mn, mx)

In [186]:
#Проверьте корректность работы функции
a = np.array([0, 2, 4, 1, 3])
closest_value(a,1.33)

(1, 4)

### 4

Напишите функцию, создающую массив первых n нечетных чисел, записанных в порядке убывания. Например, если `n=5`, то ответом будет `array([9, 7, 5, 3, 1])`.

*Функции, которые могут пригодиться при решении: `.arange()`*

In [187]:
def first_odds(n):
    rev = np.arange(1, n * 2, 2)
    return rev[::-1]

In [188]:
#Проверьте корректность работы функции
first_odds(7)


array([13, 11,  9,  7,  5,  3,  1])

### 5

Напишите функцию, вычисляющую произведение всех ненулевых диагональных элементов на диагонали данной квадратной матрицы. Например, если на вход поступает матрица
$$
\begin{pmatrix}
0 & 1 & 2\\
3 & 4 & 5\\
6 & 7 & 8\\
\end{pmatrix},
$$
то ответом будет 32.

_Функции, которые могут пригодиться при решении: `.diagonal()`, `.prod()`_

In [189]:
def diag_prod(matrix):
    d = matrix.diagonal()
    return d[d.nonzero()].prod()
    

In [191]:
#Проверьте корректность работы функции
a = np.arange(9).reshape((3,3))
diag_prod(a)

32

### 6

Напишите функцию, вычисляющую какую-нибудь первообразную данного полинома (в качестве константы возьмите ваше любимое число). Например, если на вход поступает массив коэффициентов `array([4, 6, 0, 1])`, что соответствует полиному $4x^3 + 6x^2 + 1$, на выходе получается массив коэффициентов `array([1, 2, 0, 1, -2])`, соответствующий полиному $x^4 + 2x^3 + x - 2$.

_Функции, которые могут пригодиться при решении: `.append()`_

In [95]:
def antiderivative(coefs):
    dgr = np.arange(1, coefs.shape[0] + 1)[::-1]
    new_cf = coefs / dgr
    return np.append(new_cf,7)

In [192]:
#Проверьте корректность работы функции
c = np.array([4, 6, 0, 1])
antiderivative(c)

array([1., 2., 0., 1., 7.])

### 7

Напишите функцию, делающую данную [треугольную матрицу](https://ru.wikipedia.org/wiki/%D0%A2%D1%80%D0%B5%D1%83%D0%B3%D0%BE%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F_%D0%BC%D0%B0%D1%82%D1%80%D0%B8%D1%86%D0%B0) симметричной. Например, если на вход поступает матрица
$$
\begin{pmatrix}
1 & 2 & 3 & 4\\
0 & 5 & 6 & 7\\
0 & 0 & 8 & 9\\
0 & 0 & 0 & 10\\
\end{pmatrix},
$$
то на выходе должна быть матрица
$$
\begin{pmatrix}
1 & 2 & 3 & 4\\
2 & 5 & 6 & 7\\
3 & 6 & 8 & 9\\
4 & 7 & 9 & 10\\
\end{pmatrix}.
$$

_Функции, которые могут пригодиться при решении: `.diag()`, `.diagonal()`, `.T`_

In [193]:
def make_symmetric(matrix):
    d = np.diag(matrix) * np.eye(matrix.shape[0])
    return matrix + matrix.T - d

In [196]:
#Проверьте корректность работы функции
a = np.array([[1,2,3],[0,3,4],[0,0,6]])
make_symmetric(a)

array([[1., 2., 3.],
       [2., 3., 4.],
       [3., 4., 6.]])

In [197]:
a

array([[1, 2, 3],
       [0, 3, 4],
       [0, 0, 6]])

### 8

Напишите функцию, создающую прямоугольную матрицу из m одинаковых строк, заполненных последовательными натуральными числами от a до b включительно в возрастающем порядке. Например, если m = 5, a = 3, b = 10, то на выходе будет матрица
$$
\begin{pmatrix}
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
\end{pmatrix}
$$

_Функции, которые могут пригодиться при решении: `.arange()`, `.zeros()`, а также [broadcasting rules](https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html)._

In [200]:
def construct_matrix(m, a, b):
    line = np.arange(a,b+1)
    clmn = np.zeros((m,1),int)+1
    return line * clmn

In [201]:
#Проверьте корректность работы функции
a = 4
b = 7
m = 2
construct_matrix(m, a, b)

array([[4, 5, 6, 7],
       [4, 5, 6, 7]])

### 9

Напишите функцию, вычисляющую [косинусную близость](https://en.wikipedia.org/wiki/Cosine_similarity) двух векторов. Например, если на вход поступают вектора `array([-2, 1, 0, -5, 4, 3, -3])` и `array([0, 2, -2, 10, 6, 0, 0])`, ответом будет -0.25.

_Функции, которые могут пригодиться при решении: `.dot()`, `.norm()`, `.sum()`_

In [202]:
def cosine_similarity(vec1, vec2):
    return (vec1.T @ vec2) / (np.linalg.norm(vec1) * np.linalg.norm(vec2))

In [203]:
#Проверьте корректность работы функции
a = np.array([-2, 1, 0, -5, 4, 3, -3])
b = np.array([0, 2, -2, 10, 6, 0, 0])
cosine_similarity(b, a)

-0.25